services:
  - type: web
    name: club-scheduler-node
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: KAKAO_REST_API_KEY
        sync: false
      - key: KAKAO_REDIRECT_URI
        sync: false
      - key: KAKAO_ADMIN_KEY
        sync: false
      - key: KAKAO_CLIENT_SECRET
        sync: false
